project "custos"
    files {
        "backlight.h",
        "backlight.c",
        "battery.h",
        "battery.c",
        "date.h",
        "date.c",
        "fs.h",
        "fs.c",
        "load.c",
        "load.h",
        "lua.c",
        "main.c",
        "term.h",
        "term.c",
        "test.h",
        "test.c",
        "thermal.c",
        "thermal.h",
        "utils.c",
        "utils.h",
        "window.h",
        "window.c",
    }
